[package]
name = "policycoreutils"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/SELinuxProject/selinux/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/SELinuxProject/selinux/releases/download/3.4/policycoreutils-3.4.tar.gz"
sha512 = "ded0d6fb5e3f165a893ee42411ac82616ddf37a02acaca6a8437b8f10ea12e5594bbd7bc7e3ead12df00c018078950f3fbe55604c41b0554257c4ca18f55ebb6"

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
libsemanage = { path = "../libsemanage" }
libsepol = { path = "../libsepol" }
