[package]
name = "docker-proxy"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/libnetwork/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/libnetwork/archive/f6ccccb1c082a432c2a5814aaedaca56af33d9ea/libnetwork-f6ccccb1c082a432c2a5814aaedaca56af33d9ea.tar.gz"
sha512 = "d3d9888f39a9247b6e773b0bfe63e6d248c5c155e7032cdbdd5cfacf995cb6b4cf2f0fb51e09c4554a4b994e3c3d7fc9cd2fde6cf8dda34fba6aa07218ac959c"

[build-dependencies]
glibc = { path = "../glibc" }
