[package]
name = "libcap"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"
# Changelog can be found here: https://sites.google.com/site/fullycapable/release-notes-for-libcap

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.65.tar.gz"
sha512 = "c1523d4b73bf12fee5c1518c424319d58181cab6d0436dc3d26818a906e4fe6942b476d6db7fa5e103e05b4ffcb159ac56cc7cb2fd0d89388cc375809e5289f4"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
