[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

# ECS agent
[package.metadata.build-package]
releases-url = "https://github.com/aws/amazon-ecs-agent/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.62.0/amazon-ecs-agent-v1.62.0.tar.gz"
sha512 = "df218d584ea2fc3b8707afea834fe68a186e6a23f7f1b2afdfa4797552b9ac30120229023f5e9b23b87bf62991f4b6b215dee4a5bddf7b9e66cbd47b309fc780"

# The ECS agent repository includes two CNI plugins as git submodules.  git
# archive does not include submodules, so the tarball above does not include
# the source of those plugins.  Instead, we include the CNI plugin source
# directly.
[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-cni-plugins/archive/db5864722987c34ba309e6e7a7628fd1ccad1520/amazon-ecs-cni-plugins.tar.gz"
sha512 = "550681f5cd9bdf46dd1a3353b9d328217a4d1b8697633fb70c19a0e2ddd839fb08bc764b63b1c23bc77b0d1c125ee8fbb5de0ad55628b1449261e9700e486387"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-vpc-cni-plugins/archive/199bfc65cced4951cbb6a38e6e828afa8c2b023c/amazon-vpc-cni-plugins.tar.gz"
sha512 = "ee1c2230c43fa7b8b9a25319bd334abfc08210ea8956ccc4525fe936b48b22b85df778823138d58687e847762b436daa0e0ba69c210a00b173f9b933f656386d"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# `docker-engine` is only needed at runtime, and is included in the variant
# definition.
# docker-engine = { path = "../docker-engine" }
# `iptables` is only needed at runtime, and is pulled in by `release`.
# iptables = { path = "../iptables" }
