[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
releases-url = "https://github.com/docker/cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v20.10.17/cli-20.10.17.tar.gz"
sha512 = "9c2cff7e248272e234eac9febdfd7c5c844fc65ee4b08fd4ce0f526e4fed33f2d12682d0991ef28b42977b9de2c84d7ef9c6ddd6f31c4e8c34a3985c1cea3316"

[build-dependencies]
glibc = { path = "../glibc" }
